name: workflow
on:
  workflow_dispatch:
  push:

jobs:
  felles-workflow:
    uses: navikt/flex-github-actions-workflows/.github/workflows/next-js.yml@npm-ci-production-3
    permissions:
      packages: 'write'
      contents: 'read'
      id-token: 'write'
    secrets: inherit
    with:
      base-path: syk/sykefravaer
      sentry-enabled: false
